#!/bin/bash
#BSUB -W 16:00
#BSUB -n 8
#BSUB -M 48000
#BSUB -R "span[ptile=8]"
#BSUB -e logs/train_scratch%J.err
#BSUB -o logs/train_scratch%J.out
#BSUB -q amdgpu
#BSUB -gpu "num=1"

# load modules
module load bedtools/2.29.2-wrl
module load gcc/9.3.0
module load cuda/11.7
module load samtools/1.6-wrl
module load pigz/2.6.0
module load ucsctools
source activate maxatac

# the main command

cd /data/weirauchlab/team/ngun7t/maxatac/runs

maxatac train --genome hg38 \
--arch Transformer_phuc \
--sequence /users/ngun7t/opt/maxatac/data/hg38/hg38.2bit \
--meta_file /data/weirauchlab/team/ngun7t/maxatac/training_data/meta_file.tsv \
--output /data/weirauchlab/team/ngun7t/maxatac/runs/scratch \
--prefix scratch \
--epochs 1