#!/bin/bash
#PBS -N gh_tra_c2
#PBS -l nodes=1:ppn=32:gpus=1
#PBS -l walltime=52:00:00
#PBS -j oe
#PBS -q lab_gpu

# set envirenment
source /public/software/profile.d/cuda10.0.sh
source /public/software/profile.d/python3.sh
conda activate py36

# working
cd /public/home/hengyi/guohong/MLP_RO_2022_10_15/code/model_training/mlp_training_all/mlp_c/
python3 ./all_c_s_4layers_128_64_32_1_Relu_BZ32_LR1e-4_WD1e-6_noStepLRSchedule_noBN_noResnet_noLastRelu_.py
