#!/bin/sh

### General options
### –- specify queue --
#BSUB -q p1
### -- set the job Name --
#BSUB -J train_baseline_model
### -- ask for number of cores (default: 1) --
#BSUB -n 32
### -- Select the resources: 1 gpu in exclusive process mode --
#BSUB -gpu "num=1:mode=exclusive_process"
### -- set walltime limit: hh:mm --  maximum 24 hours for GPU-queues right now
#BSUB -W 24:00
# request 5GB of system-memory
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=11800MB]"
### -- set the email address --
# please uncomment the following line and put in your e-mail address,
# if you want to receive e-mail notifications on a non-default address
#BSUB -u caap@itu.dk
### -- send notification at start --
###BSUB -B
### -- send notification at completion--
#BSUB -N
### -- Specify the output and error file. %J is the job-id --
### -- -o and -e mean append, -oo and -eo mean overwrite --
#BSUB -o /dtu/p1/johlau/Thesis-Synthex/jobs/lsf10/logs/R-train_baseline_model_%J.out
#BSUB -e /dtu/p1/johlau/Thesis-Synthex/jobs/lsf10/logs/R-train_baseline_model_%J.err
# -- end of LSF options --

nvidia-smi
# Load the cuda module
module load cuda/12.2

python3 /dtu/p1/johlau/Thesis-Synthex/classification/train_model.py --split-idx 0 --model-name baseline --radchest-samples 0 --model-dir /dtu/p1/johlau/Thesis-Synthex/models/ --data-dir /dtu/p1/johlau/Thesis-Synthex/data/ --epochs 30 --learning-rate 0.00001 --batch-size 128 
python3 /dtu/p1/johlau/Thesis-Synthex/classification/train_model.py --split-idx 1 --model-name baseline --radchest-samples 0 --model-dir /dtu/p1/johlau/Thesis-Synthex/models/ --data-dir /dtu/p1/johlau/Thesis-Synthex/data/ --epochs 30 --learning-rate 0.00001 --batch-size 128 
python3 /dtu/p1/johlau/Thesis-Synthex/classification/train_model.py --split-idx 2 --model-name baseline --radchest-samples 0 --model-dir /dtu/p1/johlau/Thesis-Synthex/models/ --data-dir /dtu/p1/johlau/Thesis-Synthex/data/ --epochs 30 --learning-rate 0.00001 --batch-size 128 
python3 /dtu/p1/johlau/Thesis-Synthex/classification/train_model.py --split-idx 3 --model-name baseline --radchest-samples 0 --model-dir /dtu/p1/johlau/Thesis-Synthex/models/ --data-dir /dtu/p1/johlau/Thesis-Synthex/data/ --epochs 30 --learning-rate 0.00001 --batch-size 128 
python3 /dtu/p1/johlau/Thesis-Synthex/classification/train_model.py --split-idx 4 --model-name baseline --radchest-samples 0 --model-dir /dtu/p1/johlau/Thesis-Synthex/models/ --data-dir /dtu/p1/johlau/Thesis-Synthex/data/ --epochs 30 --learning-rate 0.00001 --batch-size 128 
