#!/bin/bash
#PBS -N StyleGANDataPrep
#PBS -q gpu_1
#PBS -l select=1:ncpus=9:ngpus=1
#PBS -P CSCI1142
#PBS -l walltime=00:30:00
#PBS -o /mnt/lustre/users/schetty1/StyleRuns/DataPrep.out
#PBS -e /mnt/lustre/users/schetty1/StyleRuns/DataPrep.err
#PBS -m abe
#PBS -M chtsha042@myuct.ac.za
cd /home/schetty1/ 
module load chpc/python/anaconda/3-2021.11
eval "$(conda shell.bash hook)"
conda activate /mnt/lustre/users/schetty1/CondaGAN
module load chpc/cuda/11.6/PCIe/11.6 
python3 /home/schetty1/stylegan2-ada-pytorch-main/dataset_tool.py --source /home/schetty1/lustre/ImagesforResearch/XR_SHOULDERImagesforResearch\XR_SHOULDER --dest /home/schetty1/lustre/ImagesforResearch/XR_SHOULDER_STYLE --width 512 --height 512 --resize-filter=box
conda deactivate
