#!/bin/bash
#PBS group_list=cu_10039 -A cu_10039
#PBS -m n 
#PBS -l nodes=1:ppn=10,mem=16gb,walltime=252000
#PBS -N 
cd $PBS_O_WORKDIR



arr=(rntrn_lamax rntrn_lamin rntrn_lamdv rntrn_labac rntrn_lasv rntrn_laev rntrn_lapev rntrn_latef rntrn_lapef rntrn_laaef rntrn_expansionidx rntrn_aeTangent rntrn_peTangent rntrn_lape_svd rntrn_ilamax rntrn_ilamin rntrn_ilamdv rntrn_ilabac rntrn_ilasv rntrn_ilaev rntrn_ilapev)
N=${arr[${MOAB_JOBARRAYINDEX}]}



bash gwas_bolt_rtrn.sh $N
