#!/bin/bash
#PBS group_list=cu_10039 -A cu_10039
#PBS -m n 
#PBS -l nodes=1:ppn=10,mem=16gb,walltime=252000
#PBS -N 
cd $PBS_O_WORKDIR


arr=(lamax lamin lamdv labac lasv laev lapev latef lapef laaef lape_svd expansionidx aeTangent peTangent ilamax ilamin ilamdv ilabac ilasv ilaev ilapev)
#arr=(LAV.max.mL LAV.min.mL LAEF LAsvd)
#arr=(LVM.g WTglb, LVMVR)

N=${arr[${MOAB_JOBARRAYINDEX}]}
bash gwas_bolt_nopc.sh $N
