#!/bin/bash
#PBS -l select=1:ncpus=64:mpiprocs=64:mem=10GB
#PBS -l walltime=05:00:00
#PBS -q short_cpuQ
#PBS -N mt1_rep1_md
#PBS -o logs/mt1_rep1_out
#PBS -e logs/mt1_rep1_err

module load gromacs-2021.4
export OMP_NUM_THREADS=1
cd $PBS_O_WORKDIR/../mt1_rep1/4_MD

################################################################################ MD
mpirun -np 64 gmx_mpi mdrun -cpi md_plain -v -deffnm md_plain