#!/bin/bash

# DO NOT CHANGE THE QUEUE! YOU **MUST** ONLY USE THE QUEUE: short_serial
#BSUB -q airoldi

# EDIT THE EMAIL-ADDRESS BELOW TO YOUR FAS EMAIL:
#BSUB -u jbischof@fas.harvard.edu

# THE JOB ARRAY:
#BSUB -J "get_tfidf"

# THE COMMAND TO GIVE TO R, CHANGE TO THE APPROPRIATE FILENAME:
python get_tfidf_scores.py /n/airoldifs2/lab/jbischof/reuters_output/ /n/airoldifs2/lab/jbischof/reuters_output/mmm_raw_data/