#!/bin/bash

# DO NOT CHANGE THE QUEUE! YOU **MUST** ONLY USE THE QUEUE: short_serial
#BSUB -q airoldi

# EDIT THE EMAIL-ADDRESS BELOW TO YOUR FAS EMAIL:
#BSUB -u jbischof@fas.harvard.edu

# THE JOB ARRAY:
#BSUB -J "get_partition_doc_ids"

main_dir=/n/airoldifs2/lab/jbischof/reuters_output/

# THE COMMAND TO GIVE TO R, CHANGE TO THE APPROPRIATE FILENAME:
python mmm_class_functions/get_partition_doc_ids.py $main_dir
