#!/bin/bash

# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!

#SBATCH --partition=short
#SBATCH -c 1
#SBATCH --job-name=head
#SBATCH --output=logs/head.log
#SBATCH --error=logs/head.errors.log

source /users/lindgren/hjo721/job-scripts/conda.sh aminosgym

echo "this machine has $(nproc) cpus"

ray start --head --include-dashboard true --dashboard-host 0.0.0.0 --dashboard-port 5712 --node-ip-address=$(hostname)

python process_transcripts.py