#!/bin/sh

export BASE_LOG_PATH="logs"
export OLLAMA_MAX_LOADED_MODELS=2
export OLLAMA_FLASH_ATTENTION=1
export OLLAMA_NUM_PARALLEL=2

source /Users/siddarthnarayanan/Development/darwin/.venv/bin/activate

ollama serve & (sleep 10 && python run.py) & wait
