#!/bin/bash 
#SBATCH --gres=gpu:1
#SBATCH --partition=orchid 
#SBATCH --account=orchid
#SBATCH --mem=128000 
#SBATCH -o /work/scratch-pw3/ucfacc2/sbatch_logs/ss/%x_%j_%A_%a.out
#SBATCH -e /work/scratch-pw3/ucfacc2/sbatch_logs/ss/%x_%j_%A_%a.err
#SBATCH --time=5:00:00
#SBATCH --array=000-790

# Two parameters are passed to the script by the sbatch:
# 1. project_dir: The path to the project directory
# 2. scratch_dir: The path to the project scratch directory

# record the start time
start_time=$(date "+%Y-%m-%d %H:%M:%S")
echo "Script started at: $start_time"

conda activate pytorch-orchid

export N=$(printf %03d $SLURM_ARRAY_TASK_ID)
python /gws/nopw/j04/nceo_generic/nceo_ucl/TLS/tools/TLS2trees/tls2trees/semantic.py --point-cloud $scratch_dir/downsample/${N}.downsample.ply --odir $scratch_dir/fsct --verbose --buffer 5 --tile-index $project_dir/tile_index.dat

# record the end time
end_time=$(date "+%Y-%m-%d %H:%M:%S")
echo -e "Script finished at: $end_time"

# total duration time for this job
start_timestamp=$(date -d "$start_time" +%s)
end_timestamp=$(date -d "$end_time" +%s)
duration=$((end_timestamp - start_timestamp))
hours=$((duration / 3600))
minutes=$(( (duration % 3600) / 60 ))
seconds=$((duration % 60))

echo -e "Total duration: $hours:$minutes:$seconds (hh:mm:ss)"
