#! /bin/bash --login

#PBS -N EQ_Crferr_HSP
#PBS -q Std
#PBS -l nodes=2:ppn=2
#PBS -m abe
#PBS -M user.name@domain.name
#PBS -o pbs.charmm.out
#PBS -e pbs.charmm.err

#Because charmm uses shared libraries, add charmm to your default
#module list before running by typing the following:

#module initadd charmm/31b1

cd $PBS_O_WORKDIR

#simple serial charmm job
#charmm < GB.inp > GBminimization.out.$PBS_JOBID

# example: run an MPI job
cat > stream.inp << EOF
* Title Initial equilibration using Langevin dynamics and SHAKE
* prior to full dynamics and quasiharmonic NMA.
*
stream @stream
stop
EOF

export input="stream=EQUIL.INP"

which charmm.mpi.xxlarge
mpicmd charmm.mpi.xxlarge $input < stream.inp > initequil.out

