#!/bin/bash

#SBATCH --ntasks=128
#SBATCH --nodes=2
# SBATCH --mem=378240
#SBATCH --partition=highmem
#SBATCH --job-name=wake-RA
#SBATCH --time=20:00:00
#SBATCH --output=RAND-RA.out
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
# module load openmpi/4.0.5/amd
module load conda
source activate an
module load texlive

python src/DMD-RA-working.py
