#!/bin/bash

#SBATCH --ntasks=128
#SBATCH --nodes=2
#SBATCH --partition=highmem
#SBATCH --job-name=SPOD
#SBATCH --time=10:00:00
#SBATCH --output=SPOD.out
#SBATCH --exclusive
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
# module load openmpi/4.0.5/amd
module load conda
source activate an
module load texlive
# module load openmpi/4.1.4/gcc

python src/SPOD.py
