#!/bin/bash

#SBATCH -J petscinstalljob           # Job name
#SBATCH -o petscinstalljob.o%j       # Name of stdout output file
#SBATCH -e petscinstalljob.o%j       # Name of stderr error file
#SBATCH -p vm-small      # Queue (partition) name
#SBATCH -N 1               # Total # of nodes 
#SBATCH -n 1              # Total # of mpi tasks
#SBATCH -t 08:0:0        # Run time (hh:mm:ss)
##SBATCH --mail-user=myname@myschool.edu
##SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A A-ccsc       # Allocation name (req'd if you have more than 1)

# Other commands must follow all #SBATCH directives...

module list
pwd
date

./install_all.sh -j 12 -4

