#!/bin/bash

# QUEUE
#BSUB -q airoldi

# EDIT THE EMAIL-ADDRESS BELOW TO YOUR FAS EMAIL:
#BSUB -u jbischof@fas.harvard.edu

# THE JOB ARRAY:
#BSUB -J "get_ldac_data[1-10]"


# THE COMMAND TO GIVE TO R, CHANGE TO THE APPROPRIATE FILENAME:
main_dir=/n/airoldifs2/lab/jbischof/reuters_output/mmm_folds/fold${LSB_JOBINDEX}/
cutoff=500
raw_data_dir=${main_dir}mmm_raw_data/
out_dir=${raw_data_dir}ldac_data/

# Create output directory if doesn't already exist
if [ ! -d $out_dir ]
then
   mkdir $out_dir
fi

python ../mmm_class_functions/translate_data_for_ldac.py $main_dir $cutoff
